import ClipCore
import Foundation
import Observation
import ScriptCore
import StoryboardCore
import SwiftUI
import VideoUnderstanding

#if os(iOS)
import AVFoundation
import AVKit
import PhotosUI
import UniformTypeIdentifiers
import UIKit
#endif

public struct MemoryClip: Identifiable, Equatable, Sendable {
    public let id: String
    public let title: String
    public let sourceURL: URL?
    public let note: String?
    public let bodyText: String?
    public let createdAt: Date
    public let updatedAt: Date
    public let state: ClipState
    public let failureReason: String?
    public let failureRetryable: Bool
    public let indexPreview: String?
    /// Persisted ContentBreakdown (Script) JSON; nil for text/url clips or when not yet indexed.
    public let scriptJSON: String?
    /// Authoritative evidence-grounded storyboard JSON. Legacy Script remains a projection.
    public let storyboardJSON: String?
    public let activeRunID: String?
    public let qualityStatusRaw: String?
    /// Coarse content type, used to route the clip into the 剪藏 vs 拆解 library.
    public let sourceKind: ClipSourceKind

    public init(
        id: String,
        title: String,
        sourceURL: URL?,
        note: String?,
        bodyText: String?,
        createdAt: Date,
        updatedAt: Date,
        state: ClipState,
        failureReason: String?,
        failureRetryable: Bool,
        indexPreview: String?,
        scriptJSON: String? = nil,
        storyboardJSON: String? = nil,
        activeRunID: String? = nil,
        qualityStatusRaw: String? = nil,
        sourceKind: ClipSourceKind = .text
    ) {
        self.id = id
        self.title = title
        self.sourceURL = sourceURL
        self.note = note
        self.bodyText = bodyText
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.state = state
        self.failureReason = failureReason
        self.failureRetryable = failureRetryable
        self.indexPreview = indexPreview
        self.scriptJSON = scriptJSON
        self.storyboardJSON = storyboardJSON
        self.activeRunID = activeRunID
        self.qualityStatusRaw = qualityStatusRaw
        self.sourceKind = sourceKind
    }

    /// Whether this item belongs to the 拆解 (video) library rather than 剪藏 (text/url).
    public var isVideoBreakdown: Bool {
        sourceKind == .video
    }

    /// Decoded breakdown, if this clip carries a persisted script.
    public var breakdown: Script? {
        ScriptCoding.decode(json: scriptJSON)
    }

    public var storyboard: StoryboardDocumentV2? {
        guard let storyboardJSON else { return nil }
        return try? JSONDecoder().decode(StoryboardDocumentV2.self, from: Data(storyboardJSON.utf8))
    }

    /// Human-meaningful title for lists/navigation: imported videos carry a UUID temp filename as
    /// their stored title, which is noise — prefer the breakdown's AI title when the stored one is
    /// such an auto-generated name.
    public var displayTitle: String {
        if Self.isAutoGeneratedName(title), let scriptTitle = breakdown?.title,
           !scriptTitle.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return scriptTitle
        }
        return title
    }

    /// True for machine-generated import names (PHPicker temp files are bare UUIDs).
    public static func isAutoGeneratedName(_ name: String) -> Bool {
        UUID(uuidString: name.trimmingCharacters(in: .whitespacesAndNewlines)) != nil
    }

    /// Copy/share text handed off to external generators (豆包 / 即梦). Prefers the
    /// structured breakdown rendering, falling back to the plain indexed body text.
    public var handoffText: String {
        if let breakdown {
            return ScriptRendering.indexableText(breakdown)
        }
        return bodyText ?? ""
    }
}

public struct MemoryNavigationTarget: Identifiable, Hashable, Sendable {
    public var id: String { "\(clipID)#\(chunkID)" }
    public let clipID: String
    public let chunkID: String

    public init(clipID: String, chunkID: String) {
        self.clipID = clipID
        self.chunkID = chunkID
    }
}

public struct MemoryClient: Sendable {
    public let loadItems: @Sendable () async throws -> [MemoryClip]
    public let digestPending: @Sendable () async throws -> Void
    public let retryClip: @Sendable (String) async throws -> Void
    public let importVideo: @Sendable (URL) async throws -> Void
    public let addClip: @Sendable (MemoryCaptureInput) async throws -> Void
    public let deleteClip: @Sendable (String) async throws -> Void
    public let editClip: @Sendable (String, String) async throws -> Void
    /// Structured breakdown edit: applies the transform to the persisted script, re-indexes, and
    /// returns the updated script for immediate display.
    public let updateScript: @Sendable (String, @escaping @Sendable (Script) -> Script) async throws -> Script
    /// AI re-analysis: re-derives title/summary/爆点结构 from corrected 台词+字幕+背景; returns the
    /// updated script.
    public let reanalyzeScript: @Sendable (String) async throws -> Script
    /// Exports Markdown/JSON/CSV/PDF/reference frames from the authoritative V2 document.
    public let exportStoryboard: @Sendable (String) async throws -> [URL]
    public let editStoryboardShot: @Sendable (String, Int, StoryboardShotEditCommand) async throws -> StoryboardEditPresentation

    public init(
        loadItems: @escaping @Sendable () async throws -> [MemoryClip],
        digestPending: @escaping @Sendable () async throws -> Void,
        retryClip: @escaping @Sendable (String) async throws -> Void,
        importVideo: @escaping @Sendable (URL) async throws -> Void = { _ in },
        addClip: @escaping @Sendable (MemoryCaptureInput) async throws -> Void = { _ in },
        deleteClip: @escaping @Sendable (String) async throws -> Void = { _ in },
        editClip: @escaping @Sendable (String, String) async throws -> Void = { _, _ in },
        updateScript: @escaping @Sendable (String, @escaping @Sendable (Script) -> Script) async throws -> Script = { _, _ in
            throw MemoryClientError.editingUnavailable
        },
        reanalyzeScript: @escaping @Sendable (String) async throws -> Script = { _ in
            throw MemoryClientError.editingUnavailable
        },
        exportStoryboard: @escaping @Sendable (String) async throws -> [URL] = { _ in
            throw MemoryClientError.exportUnavailable
        },
        editStoryboardShot: @escaping @Sendable (String, Int, StoryboardShotEditCommand) async throws -> StoryboardEditPresentation = { _, _, _ in
            throw MemoryClientError.editingUnavailable
        }
    ) {
        self.loadItems = loadItems
        self.digestPending = digestPending
        self.retryClip = retryClip
        self.importVideo = importVideo
        self.addClip = addClip
        self.deleteClip = deleteClip
        self.editClip = editClip
        self.updateScript = updateScript
        self.reanalyzeScript = reanalyzeScript
        self.exportStoryboard = exportStoryboard
        self.editStoryboardShot = editStoryboardShot
    }

    public static let empty = MemoryClient(
        loadItems: { [] },
        digestPending: {},
        retryClip: { _ in },
        importVideo: { _ in },
        addClip: { _ in },
        deleteClip: { _ in },
        editClip: { _, _ in }
    )
}

public enum StoryboardShotEditCommand: Hashable, Sendable {
    case split(atSeconds: Double)
    case mergeWithNext
    case editDialogue(String?)
    case moveEndBoundary(toSeconds: Double)
    case editPlan(StoryboardPlanEditValues)
    case undo
    case reanalyze
}

public struct StoryboardEditPresentation: Sendable {
    public let script: Script
    public let document: StoryboardDocumentV2
    public let changedShotIDs: [String]
    public let changedFields: [String]
    public let invalidatedStages: [String]
    public let remapSummary: String?

    public init(
        script: Script,
        document: StoryboardDocumentV2,
        changedShotIDs: [String],
        changedFields: [String],
        invalidatedStages: [String],
        remapSummary: String?
    ) {
        self.script = script
        self.document = document
        self.changedShotIDs = changedShotIDs
        self.changedFields = changedFields
        self.invalidatedStages = invalidatedStages
        self.remapSummary = remapSummary
    }
}

public struct StoryboardPlanEditValues: Hashable, Sendable {
    public let purpose: String?
    public let subjectAction: String?
    public let dialogueOrVO: String?
    public let onScreenCopy: String?
    public let productionNotes: String?

    public init(
        purpose: String?,
        subjectAction: String?,
        dialogueOrVO: String?,
        onScreenCopy: String?,
        productionNotes: String?
    ) {
        self.purpose = purpose
        self.subjectAction = subjectAction
        self.dialogueOrVO = dialogueOrVO
        self.onScreenCopy = onScreenCopy
        self.productionNotes = productionNotes
    }

    public var domainValues: [EditablePlanField: String?] {
        [
            .purpose: purpose,
            .subjectAction: subjectAction,
            .dialogueOrVO: dialogueOrVO,
            .onScreenCopy: onScreenCopy,
            .productionNotes: productionNotes,
        ]
    }
}

public enum MemoryClientError: Error, LocalizedError {
    case editingUnavailable
    case exportUnavailable

    public var errorDescription: String? {
        switch self {
        case .editingUnavailable: "剧本编辑暂不可用。"
        case .exportUnavailable: "证据分镜尚未生成，无法导出。"
        }
    }
}

/// In-app 剪藏 capture input (text snippet or a URL to fetch).
public enum MemoryCaptureInput: Sendable, Equatable {
    case text(String)
    case url(URL)
}

public enum MemoryVideoImportSelection: Sendable, Equatable {
    case cancelled
    case file(URL)
}

/// The two first-class libraries backed by the same store: 剪藏 (text/url knowledge) and
/// 拆解 (video breakdowns). Each tab renders the shared MemoryViewModel filtered by kind.
public enum MemoryLibraryKind: Sendable, Hashable {
    case clips
    case studio

    public var title: String {
        switch self {
        case .clips: "剪藏"
        case .studio: "拆解"
        }
    }

    var sourceKinds: Set<ClipSourceKind> {
        switch self {
        case .clips: [.text, .url]
        case .studio: [.video]
        }
    }
}

@MainActor
@Observable
public final class MemoryViewModel {
    public private(set) var items: [MemoryClip] = []
    public private(set) var isRefreshing = false
    public private(set) var errorMessage: String?

    @ObservationIgnored private let client: MemoryClient

    public init(client: MemoryClient = .empty) {
        self.client = client
    }

    /// Items for one library tab (剪藏 vs 拆解), filtered from the shared store.
    public func items(for kind: MemoryLibraryKind) -> [MemoryClip] {
        items.filter { kind.sourceKinds.contains($0.sourceKind) }
    }

    public func refresh() async {
        guard !isRefreshing else { return }
        isRefreshing = true
        defer { isRefreshing = false }
        do {
            items = try await client.loadItems()
            errorMessage = nil
        } catch {
            errorMessage = String(describing: error)
        }
    }

    /// Shows the list IMMEDIATELY, then runs the digest — which can take minutes for a queued
    /// video (OCR + ASR + VLM) — WITHOUT holding `isRefreshing`, and refreshes again for results.
    /// Holding the flag across the digest used to blank the library and disable the toolbar for
    /// the whole run ("右上角点不了" while a video was being 拆解 at launch).
    public func digestAndRefresh() async {
        await refresh()
        do {
            try await client.digestPending()
            errorMessage = nil
        } catch {
            errorMessage = String(describing: error)
        }
        await refresh()
    }

    public func retry(_ item: MemoryClip) async {
        do {
            try await client.retryClip(item.id)
            errorMessage = nil
        } catch {
            errorMessage = String(describing: error)
            return
        }
        await digestAndRefresh()
    }

    public func importVideo(_ selection: MemoryVideoImportSelection) async {
        guard case let .file(url) = selection else {
            return
        }

        isRefreshing = true
        defer { isRefreshing = false }
        do {
            try await client.importVideo(url)
            items = try await client.loadItems()
            errorMessage = nil
        } catch {
            errorMessage = String(describing: error)
        }
    }

    public func addClip(_ input: MemoryCaptureInput) async {
        do {
            try await client.addClip(input)
            errorMessage = nil
        } catch {
            errorMessage = String(describing: error)
            return
        }
        await digestAndRefresh()
    }

    public func delete(_ item: MemoryClip) async {
        guard !isRefreshing else { return }
        isRefreshing = true
        defer { isRefreshing = false }
        // Optimistic removal so the row disappears immediately.
        items.removeAll { $0.id == item.id }
        do {
            try await client.deleteClip(item.id)
            items = try await client.loadItems()
            errorMessage = nil
        } catch {
            errorMessage = String(describing: error)
            items = (try? await client.loadItems()) ?? items
        }
    }

    /// Saves user-corrected content for a clip and re-indexes it, so 问答 uses the fixed text.
    public func editContent(_ item: MemoryClip, newText: String) async {
        guard !isRefreshing else { return }
        let trimmed = newText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        isRefreshing = true
        defer { isRefreshing = false }
        do {
            try await client.editClip(item.id, trimmed)
            items = try await client.loadItems()
            errorMessage = nil
        } catch {
            errorMessage = String(describing: error)
        }
    }

    /// Applies a structured breakdown edit (manual correction), refreshes the store, and returns
    /// the updated script for immediate in-place display. nil on failure (errorMessage set).
    public func updateScript(
        _ item: MemoryClip,
        transform: @escaping @Sendable (Script) -> Script
    ) async -> Script? {
        do {
            let updated = try await client.updateScript(item.id, transform)
            items = (try? await client.loadItems()) ?? items
            errorMessage = nil
            return updated
        } catch {
            errorMessage = String(describing: error)
            return nil
        }
    }

    /// AI re-analysis of a breakdown's understanding fields from its corrected facts + 背景.
    public func reanalyzeScript(_ item: MemoryClip) async -> Script? {
        do {
            let updated = try await client.reanalyzeScript(item.id)
            items = (try? await client.loadItems()) ?? items
            errorMessage = nil
            return updated
        } catch {
            errorMessage = String(describing: error)
            return nil
        }
    }

    public func exportStoryboard(_ item: MemoryClip) async -> [URL]? {
        do {
            let urls = try await client.exportStoryboard(item.id)
            errorMessage = nil
            return urls
        } catch {
            errorMessage = String(describing: error)
            return nil
        }
    }

    public func editStoryboardShot(
        _ item: MemoryClip,
        shotIndex: Int,
        command: StoryboardShotEditCommand
    ) async -> StoryboardEditPresentation? {
        do {
            let script = try await client.editStoryboardShot(item.id, shotIndex, command)
            items = (try? await client.loadItems()) ?? items
            errorMessage = nil
            return script
        } catch {
            errorMessage = String(describing: error)
            return nil
        }
    }

    public func reportImportFailure(_ error: Error) {
        errorMessage = String(describing: error)
    }
}

/// Memory surface — the app-side digest status timeline.
public struct MemoryView: View {
    @State private var viewModel: MemoryViewModel
    @Binding private var navigationTarget: MemoryNavigationTarget?
    @State private var isShowingVideoPicker = false
    @State private var isShowingClipCapture = false
    private let kind: MemoryLibraryKind
    /// Invoked by a detail view's 问这条 action to open 问答 focused on that clip (wired by the shell).
    private let onAskAboutClip: (MemoryClip) -> Void

    public init(
        kind: MemoryLibraryKind = .clips,
        viewModel: MemoryViewModel = MemoryViewModel(),
        navigationTarget: Binding<MemoryNavigationTarget?> = .constant(nil),
        onAskAboutClip: @escaping (MemoryClip) -> Void = { _ in }
    ) {
        self.kind = kind
        _viewModel = State(initialValue: viewModel)
        _navigationTarget = navigationTarget
        self.onAskAboutClip = onAskAboutClip
    }

    private var items: [MemoryClip] {
        viewModel.items(for: kind)
    }

    public var body: some View {
        Group {
            if items.isEmpty {
                ContentUnavailableView(
                    emptyTitle,
                    systemImage: kind == .studio ? "film.stack" : "tray.full",
                    description: Text(emptyDescription)
                )
            } else {
                List(items) { item in
                    NavigationLink {
                        MemoryDetailView(
                            item: item,
                            retry: { Task { await viewModel.retry(item) } },
                            onSaveEdit: { newText in Task { await viewModel.editContent(item, newText: newText) } },
                            onAskAboutClip: onAskAboutClip,
                            onUpdateScript: { transform in await viewModel.updateScript(item, transform: transform) },
                            onReanalyze: { await viewModel.reanalyzeScript(item) },
                            onExportStoryboard: { await viewModel.exportStoryboard(item) },
                            onEditStoryboardShot: { index, command in
                                await viewModel.editStoryboardShot(item, shotIndex: index, command: command)
                            }
                        )
                    } label: {
                        MemoryRow(item: item)
                    }
                    .swipeActions(edge: .trailing, allowsFullSwipe: true) {
                        Button(role: .destructive) {
                            Task { await viewModel.delete(item) }
                        } label: {
                            Label("删除", systemImage: "trash")
                        }
                    }
                }
                .refreshable {
                    await viewModel.digestAndRefresh()
                }
            }
        }
        .overlay(alignment: .bottom) {
            if let errorMessage = viewModel.errorMessage {
                Text(errorMessage)
                    .font(.footnote)
                    .foregroundStyle(.white)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(.red, in: Capsule())
                    .padding()
            }
        }
        .toolbar {
            if kind == .clips {
                ToolbarItem(placement: .automatic) {
                    Button {
                        isShowingClipCapture = true
                    } label: {
                        Label("剪藏", systemImage: "plus")
                    }
                    .accessibilityLabel("新建剪藏")
                }
            }
            #if os(iOS)
            if kind == .studio {
                ToolbarItem(placement: .automatic) {
                    Button {
                        isShowingVideoPicker = true
                    } label: {
                        Label("导入视频", systemImage: "video.badge.plus")
                    }
                    .accessibilityLabel("导入视频")
                }
            }
            #endif
            ToolbarItem(placement: .automatic) {
                Button {
                    Task { await viewModel.digestAndRefresh() }
                } label: {
                    Image(systemName: "arrow.clockwise")
                }
                .accessibilityLabel("Refresh clips")
                .disabled(viewModel.isRefreshing)
            }
        }
        #if os(iOS)
        .sheet(isPresented: $isShowingVideoPicker) {
            VideoPickerView { result in
                isShowingVideoPicker = false
                switch result {
                case let .success(selection):
                    Task { await viewModel.importVideo(selection) }
                case let .failure(error):
                    viewModel.reportImportFailure(error)
                }
            }
        }
        #endif
        .sheet(isPresented: $isShowingClipCapture) {
            ClipCaptureSheet { input in
                isShowingClipCapture = false
                Task { await viewModel.addClip(input) }
            } cancel: {
                isShowingClipCapture = false
            }
        }
        .navigationTitle(kind.title)
        .navigationDestination(item: $navigationTarget) { target in
            if let item = viewModel.items.first(where: { $0.id == target.clipID }) {
                MemoryDetailView(
                    item: item,
                    highlightedChunkID: target.chunkID,
                    retry: { Task { await viewModel.retry(item) } },
                    onSaveEdit: { newText in Task { await viewModel.editContent(item, newText: newText) } },
                    onAskAboutClip: onAskAboutClip,
                    onUpdateScript: { transform in await viewModel.updateScript(item, transform: transform) },
                    onReanalyze: { await viewModel.reanalyzeScript(item) },
                    onExportStoryboard: { await viewModel.exportStoryboard(item) },
                    onEditStoryboardShot: { index, command in
                        await viewModel.editStoryboardShot(item, shotIndex: index, command: command)
                    }
                )
            } else {
                ContentUnavailableView("未找到内容", systemImage: "doc.text.magnifyingglass")
            }
        }
        .task {
            await viewModel.digestAndRefresh()
        }
        .onChange(of: navigationTarget) { _, target in
            guard target != nil else { return }
            Task { await viewModel.refresh() }
        }
    }

    private var emptyTitle: String {
        kind == .studio ? "还没有视频拆解" : "还没有剪藏"
    }

    private var emptyDescription: String {
        switch kind {
        case .studio:
            "点右上角导入本地视频，端侧/云端会拆出爆点结构与分镜剧本。"
        case .clips:
            "从任意 app 分享文本或链接到 Engram，之后就能问出来。"
        }
    }
}

#if os(iOS)
private enum VideoPickerError: Error, Equatable, Sendable {
    case providerFailed(String)
    case copyFailed(String)
}

private struct VideoPickerView: UIViewControllerRepresentable {
    let onCompletion: @MainActor @Sendable (Result<MemoryVideoImportSelection, VideoPickerError>) -> Void

    func makeUIViewController(context: Context) -> PHPickerViewController {
        var configuration = PHPickerConfiguration(photoLibrary: .shared())
        configuration.filter = .videos
        configuration.selectionLimit = 1
        let picker = PHPickerViewController(configuration: configuration)
        picker.delegate = context.coordinator
        return picker
    }

    func updateUIViewController(_ uiViewController: PHPickerViewController, context: Context) {
        _ = uiViewController
        _ = context
    }

    func makeCoordinator() -> Coordinator {
        Coordinator(onCompletion: onCompletion)
    }

    final class Coordinator: NSObject, PHPickerViewControllerDelegate {
        private let onCompletion: @MainActor @Sendable (Result<MemoryVideoImportSelection, VideoPickerError>) -> Void

        init(onCompletion: @escaping @MainActor @Sendable (Result<MemoryVideoImportSelection, VideoPickerError>) -> Void) {
            self.onCompletion = onCompletion
        }

        func picker(_ picker: PHPickerViewController, didFinishPicking results: [PHPickerResult]) {
            _ = picker
            guard let provider = results.first?.itemProvider else {
                onCompletion(.success(.cancelled))
                return
            }

            let typeIdentifier = provider.registeredTypeIdentifiers.first {
                UTType($0)?.conforms(to: .movie) == true
            } ?? UTType.movie.identifier

            provider.loadFileRepresentation(forTypeIdentifier: typeIdentifier) { [onCompletion] url, error in
                if let error {
                    Self.complete(.failure(.providerFailed(String(describing: error))), onCompletion: onCompletion)
                    return
                }

                guard let url else {
                    Self.complete(.success(.cancelled), onCompletion: onCompletion)
                    return
                }

                do {
                    let stableURL = try Self.copyPickerTemporaryFile(url)
                    Self.complete(.success(.file(stableURL)), onCompletion: onCompletion)
                } catch {
                    Self.complete(.failure(.copyFailed(String(describing: error))), onCompletion: onCompletion)
                }
            }
        }

        private static func complete(
            _ result: Result<MemoryVideoImportSelection, VideoPickerError>,
            onCompletion: @escaping @MainActor @Sendable (Result<MemoryVideoImportSelection, VideoPickerError>) -> Void
        ) {
            Task { @MainActor in
                onCompletion(result)
            }
        }

        private static func copyPickerTemporaryFile(_ url: URL) throws -> URL {
            let directory = FileManager.default.temporaryDirectory
                .appendingPathComponent("EngramPickedVideos", isDirectory: true)
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            let pathExtension = url.pathExtension.isEmpty ? "mov" : url.pathExtension
            let destination = directory
                .appendingPathComponent(UUID().uuidString, isDirectory: false)
                .appendingPathExtension(pathExtension)
            try? FileManager.default.removeItem(at: destination)
            try FileManager.default.copyItem(at: url, to: destination)
            return destination
        }
    }
}
#endif

private struct ClipCaptureSheet: View {
    enum Mode: String, CaseIterable, Identifiable {
        case text = "文本"
        case url = "链接"
        var id: String { rawValue }
    }

    let submit: (MemoryCaptureInput) -> Void
    let cancel: () -> Void

    @State private var mode: Mode = .text
    @State private var text = ""
    @State private var urlString = ""

    var body: some View {
        NavigationStack {
            Form {
                Picker("类型", selection: $mode) {
                    ForEach(Mode.allCases) { Text($0.rawValue).tag($0) }
                }
                .pickerStyle(.segmented)

                switch mode {
                case .text:
                    Section("文本") {
                        TextField("粘贴要剪藏的文本", text: $text, axis: .vertical)
                            .lineLimit(4...12)
                    }
                case .url:
                    Section("链接") {
                        TextField("https://…", text: $urlString)
                            .autocorrectionDisabled()
                            .textContentType(.URL)
                            #if os(iOS)
                            .textInputAutocapitalization(.never)
                            #endif
                        Text("剪藏时会联网抓取一次正文,之后问答离线。")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }
            .navigationTitle("新建剪藏")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("取消", action: cancel)
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("保存") {
                        if let input = makeInput() {
                            submit(input)
                        }
                    }
                    .disabled(makeInput() == nil)
                }
            }
        }
    }

    private func makeInput() -> MemoryCaptureInput? {
        switch mode {
        case .text:
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed.isEmpty ? nil : .text(trimmed)
        case .url:
            let trimmed = urlString.trimmingCharacters(in: .whitespaces)
            guard let url = URL(string: trimmed), let scheme = url.scheme?.lowercased(),
                  scheme == "http" || scheme == "https" else {
                return nil
            }
            return .url(url)
        }
    }
}

private struct MemoryRow: View {
    let item: MemoryClip

    var body: some View {
        HStack(alignment: .top, spacing: 10) {
            #if os(iOS)
            // 拆解 rows lead with a poster frame (first shot midpoint) — instantly recognizable,
            // unlike the UUID filenames these clips used to be listed by.
            if item.isVideoBreakdown, let url = item.sourceURL, url.isFileURL {
                ShotThumbnail(
                    videoURL: url,
                    seconds: posterSeconds,
                    startSeconds: posterShot?.startSeconds ?? 0,
                    endSeconds: posterShot?.endSeconds ?? max(0.1, posterSeconds),
                    shotIndex: 0
                )
            }
            #endif

            VStack(alignment: .leading, spacing: 4) {
                HStack(alignment: .firstTextBaseline) {
                    Text(item.displayTitle)
                        .font(.headline)
                        .lineLimit(2)
                    Spacer(minLength: 12)
                    StateBadge(state: item.state)
                }

                if let subtitle, !subtitle.isEmpty {
                    Text(subtitle)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .lineLimit(2)
                }

                Text(metaLine)
                    .font(.caption)
                    .foregroundStyle(.tertiary)
                    .lineLimit(1)
            }
        }
        .padding(.vertical, 4)
    }

    /// 拆解: the breakdown summary; 剪藏: body preview. Raw file paths are never shown.
    private var subtitle: String? {
        if item.isVideoBreakdown {
            let summary = item.breakdown?.summary.trimmingCharacters(in: .whitespacesAndNewlines)
            if let summary, !summary.isEmpty { return summary }
            return nil
        }
        return item.bodyText?.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Compact facts: web host for 剪藏 links, 分镜 count for 拆解, plus the date.
    private var metaLine: String {
        var parts: [String] = []
        if item.isVideoBreakdown {
            if let count = item.breakdown?.shots.count, count > 0 {
                parts.append("分镜 \(count)")
            }
        } else if let host = item.sourceURL?.host(), !host.isEmpty {
            parts.append(host)
        }
        parts.append(item.createdAt.formatted(date: .abbreviated, time: .omitted))
        return parts.joined(separator: " · ")
    }

    private var posterSeconds: Double {
        guard let first = posterShot else { return 0.5 }
        return (first.startSeconds + max(first.startSeconds, first.endSeconds)) / 2
    }

    private var posterShot: StoryboardShot? {
        item.breakdown?.shots.min(by: { $0.index < $1.index })
    }
}

private struct MemoryDetailView: View {
    let item: MemoryClip
    var highlightedChunkID: String? = nil
    let retry: () -> Void
    var onSaveEdit: (String) -> Void = { _ in }
    var onAskAboutClip: (MemoryClip) -> Void = { _ in }
    /// Structured breakdown edit; returns the updated script (nil on failure) for in-place display.
    var onUpdateScript: (@escaping @Sendable (Script) -> Script) async -> Script? = { _ in nil }
    /// AI re-analysis from corrected facts + 背景; returns the updated script.
    var onReanalyze: () async -> Script? = { nil }
    var onExportStoryboard: () async -> [URL]? = { nil }
    var onEditStoryboardShot: (Int, StoryboardShotEditCommand) async -> StoryboardEditPresentation? = { _, _ in nil }

    @State private var isEditing = false
    @State private var editDraft = ""
    @State private var shareParcel: ShareParcel?
    // The latest edited/re-analyzed script — `item` is an immutable row copy, so edits display
    // from this override until the list refreshes.
    @State private var revisedScript: Script?
    @State private var revisedStoryboard: StoryboardDocumentV2?
    @State private var editFeedback: String?
    @State private var isEditingContext = false
    @State private var contextDraft = ""
    @State private var isEditingFacts = false
    @State private var factsDraft = ScriptFactsDraft()
    @State private var editingShot: StoryboardShot?
    @State private var editingBoundary: BoundaryEditContext?
    @State private var editingPlan: PlanEditContext?

    private var displayedBreakdown: Script? {
        revisedScript ?? item.breakdown
    }

    private var displayedStoryboard: StoryboardDocumentV2? {
        revisedStoryboard ?? item.storyboard
    }

    var body: some View {
        List {
            if let failureReason = item.failureReason {
                Section("失败原因") {
                    Text(failureReason)
                    if item.failureRetryable {
                        Button("重试") {
                            retry()
                        }
                    }
                }
            }

            if let editFeedback {
                Section("本次分镜变更") {
                    Text(editFeedback).font(.footnote)
                }
            }

            if let breakdown = displayedBreakdown {
                // A degraded breakdown (vision failed → transcript-only, bad-JSON fallback, partial
                // deep coverage) must be visibly marked — it used to look identical to a full 拆解.
                if let note = breakdown.degradationNote, !note.isEmpty {
                    Section {
                        Label {
                            Text(note)
                                .font(.footnote)
                        } icon: {
                            Image(systemName: "exclamationmark.triangle.fill")
                                .foregroundStyle(.orange)
                        }
                        Text("这是降级结果，非完整拆解。可删除后重新导入，或修复设置后重试。")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    } header: {
                        Text("画面理解未完全生效")
                    }
                }

                // ONE conversational entry: questions AND corrections go through the focused chat
                // ("这是电竞梗…"/"分镜3台词应该是…" → the AI applies the fix). Micro-edits live on
                // long-press menus; no button farm.
                Section {
                    Button {
                        onAskAboutClip(item)
                    } label: {
                        Label("和 AI 聊这条 · 提问或订正", systemImage: "bubble.left.and.text.bubble.right")
                            .font(.body.weight(.medium))
                    }
                } footer: {
                    Text("直接说哪里不对（背景/台词/爆点…），AI 会当场修正拆解；长按各区块可手动编辑。")
                }

                if let storyboard = displayedStoryboard {
                    Section("证据分镜") {
                        LabeledContent("质量", value: item.qualityStatusRaw ?? "unknown")
                        LabeledContent("实际模式", value: storyboard.source.actualCloudMode.rawValue)
                        LabeledContent("完整视频上传", value: storyboard.source.mediaUploaded ? "是" : "否")
                        if let note = storyboard.source.degradationNote, !note.isEmpty {
                            Label(note, systemImage: "exclamationmark.triangle")
                                .font(.caption)
                                .foregroundStyle(.orange)
                        }
                    }

                    Section("原片事实 · SourceBreakdown") {
                        ForEach(storyboard.shotGraph.shots.indices, id: \.self) { index in
                            StoryboardSourceShotRow(document: storyboard, index: index)
                        }
                    }

                    Section("内容分析") {
                        Text(storyboard.contentAnalysis.summary)
                        if !storyboard.contentAnalysis.themes.isEmpty {
                            LabeledContent("主题", value: storyboard.contentAnalysis.themes.joined(separator: "、"))
                        }
                        if let hook = storyboard.contentAnalysis.hook {
                            LabeledContent("Hook", value: hook)
                        }
                    }

                    Section("重拍分镜 · ProductionPlan") {
                        ForEach(storyboard.shots) { shot in
                            VStack(alignment: .leading, spacing: 5) {
                                Text(shot.id.rawValue).font(.subheadline.weight(.semibold))
                                Text(shot.productionPlan?.subjectAction ?? "待确认")
                                if let dialogue = shot.productionPlan?.dialogueOrVO {
                                    Text("台词：\(dialogue)").font(.footnote)
                                }
                                if let locks = shot.productionPlan?.userLockedFields, !locks.isEmpty {
                                    Text("人工锁：\(locks.sorted().joined(separator: ", "))")
                                        .font(.caption2)
                                        .foregroundStyle(.blue)
                                }
                            }
                            .contextMenu {
                                Button {
                                    editingPlan = PlanEditContext(shotIndex: max(0, (shot.productionPlan?.displayNumber ?? 1) - 1), plan: shot.productionPlan)
                                } label: {
                                    Label("编辑专业字段…", systemImage: "slider.horizontal.3")
                                }
                            }
                        }
                    }
                }

                if let context = breakdown.userContext, !context.isEmpty {
                    Section("背景") {
                        Text(context)
                            .font(.footnote)
                            .textSelection(.enabled)
                            .contextMenu {
                                Button {
                                    contextDraft = context
                                    isEditingContext = true
                                } label: {
                                    Label("编辑背景", systemImage: "square.and.pencil")
                                }
                            }
                    }
                }

                if let hook = breakdown.hookStructure {
                    Section("爆点结构") {
                        HookStructureView(hook: hook)
                            .contextMenu {
                                Button {
                                    factsDraft = ScriptFactsDraft(script: breakdown)
                                    isEditingFacts = true
                                } label: {
                                    Label("编辑标题/摘要/剧情点", systemImage: "list.bullet.rectangle")
                                }
                            }
                    }
                }

                if !breakdown.characters.isEmpty {
                    Section("人物") {
                        ForEach(Array(breakdown.characters.enumerated()), id: \.offset) { _, profile in
                            Text(profile)
                                .textSelection(.enabled)
                        }
                    }
                }

                if !breakdown.visualElements.isEmpty {
                    Section("视觉元素") {
                        Text(breakdown.visualElements.joined(separator: "、"))
                            .textSelection(.enabled)
                    }
                }

                if !breakdown.shots.isEmpty {
                    Section("分镜 (\(breakdown.shots.count))") {
                        ForEach(breakdown.shots.sorted { $0.index < $1.index }, id: \.index) { shot in
                            ShotRowView(shot: shot, videoURL: breakdownVideoURL)
                                .contextMenu {
                                    if !shot.onScreenText.isEmpty {
                                        Button {
                                            let caption = shot.onScreenText.joined(separator: "，")
                                            Task {
                                                let index = shot.index
                                                if let updated = await onEditStoryboardShot(index, .editDialogue(caption)) {
                                                    apply(updated)
                                                }
                                            }
                                        } label: {
                                            Label("用字幕替换台词", systemImage: "text.insert")
                                        }
                                    }
                                    Button {
                                        editingShot = shot
                                    } label: {
                                        Label("订正台词…", systemImage: "pencil")
                                    }
                                    Button {
                                        Task {
                                            if let updated = await onEditStoryboardShot(shot.index, .reanalyze) {
                                                apply(updated)
                                            }
                                        }
                                    } label: {
                                        Label("只重新分析此镜头", systemImage: "sparkles")
                                    }
                                    if shot.index < breakdown.shots.count - 1 {
                                        Button {
                                            let nextEnd = breakdown.shots[shot.index + 1].endSeconds
                                            editingBoundary = BoundaryEditContext(
                                                shotIndex: shot.index,
                                                lower: shot.startSeconds + 0.05,
                                                upper: max(shot.startSeconds + 0.1, nextEnd - 0.05),
                                                value: shot.endSeconds
                                            )
                                        } label: {
                                            Label("调整结束边界…", systemImage: "arrow.left.and.right")
                                        }
                                    }
                                    Button {
                                        Task {
                                            let midpoint = (shot.startSeconds + shot.endSeconds) / 2
                                            if let updated = await onEditStoryboardShot(shot.index, .split(atSeconds: midpoint)) {
                                                apply(updated)
                                            }
                                        }
                                    } label: {
                                        Label("在中点拆分镜头", systemImage: "scissors")
                                    }
                                    if shot.index < breakdown.shots.count - 1 {
                                        Button {
                                            Task {
                                                if let updated = await onEditStoryboardShot(shot.index, .mergeWithNext) {
                                                    apply(updated)
                                                }
                                            }
                                        } label: {
                                            Label("与下一镜头合并", systemImage: "rectangle.2.swap")
                                        }
                                    }
                                    #if os(iOS)
                                    if let narration = shot.narration, !narration.isEmpty {
                                        Button {
                                            UIPasteboard.general.string = narration
                                        } label: {
                                            Label("复制台词", systemImage: "doc.on.doc")
                                        }
                                    }
                                    #endif
                                }
                        }
                    }
                }
            } else if let bodyText = item.bodyText, !bodyText.isEmpty {
                Section("原文") {
                    Text(bodyText)
                        .textSelection(.enabled)
                }
            }

            // Metadata is rarely needed — it lives at the bottom so content leads.
            Section("信息") {
                LabeledContent("状态") {
                    StateBadge(state: item.state)
                }
                LabeledContent("更新时间", value: item.updatedAt.formatted(date: .abbreviated, time: .shortened))
                // Only web sources are meaningful to the user; local file paths are noise.
                if let sourceURL = item.sourceURL, !sourceURL.isFileURL {
                    LabeledContent("来源", value: sourceURL.absoluteString)
                }
                if let note = item.note, !note.isEmpty {
                    LabeledContent("备注", value: note)
                }
            }

            if let highlightedChunkID, !highlightedChunkID.isEmpty {
                Section("引用") {
                    LabeledContent("内容", value: item.id)
                    LabeledContent("片段", value: highlightedChunkID)
                }
            }
        }
        .navigationTitle(item.displayTitle)
        .toolbar {
            if canAsk {
                ToolbarItem(placement: .automatic) {
                    Button {
                        onAskAboutClip(item)
                    } label: {
                        Label("问这条", systemImage: "questionmark.bubble")
                    }
                    .accessibilityLabel("只问这条内容")
                }
            }
            if canEditContent {
                ToolbarItem(placement: .automatic) {
                    Button {
                        editDraft = item.bodyText ?? ""
                        isEditing = true
                    } label: {
                        Label("编辑", systemImage: "pencil")
                    }
                    .accessibilityLabel("编辑内容")
                }
            }
            if !item.handoffText.isEmpty {
                ToolbarItem(placement: .automatic) {
                    Menu {
                        ShareLink("分享剧本", item: item.handoffText)
                        #if os(iOS)
                        if breakdownVideoURL != nil, let shots = displayedBreakdown?.shots, !shots.isEmpty {
                            Button {
                                Task { await prepareShareWithFrames(shots) }
                            } label: {
                                Label("分享（附分镜截图）", systemImage: "photo.on.rectangle.angled")
                            }
                        }
                        Button {
                            Task {
                                if let urls = await onExportStoryboard(), !urls.isEmpty {
                                    shareParcel = ShareParcel(items: urls)
                                }
                            }
                        } label: {
                            Label("导出五类分镜文件", systemImage: "archivebox")
                        }
                        Button {
                            UIPasteboard.general.string = item.handoffText
                        } label: {
                            Label("复制全文", systemImage: "doc.on.doc")
                        }
                        #endif
                    } label: {
                        Label("投喂", systemImage: "square.and.arrow.up")
                    }
                    .accessibilityLabel("复制或分享剧本，投喂到豆包/即梦")
                }
            }
            if displayedStoryboard != nil {
                ToolbarItem(placement: .automatic) {
                    Menu {
                        Button {
                            Task {
                                if let updated = await onEditStoryboardShot(0, .undo) {
                                    apply(updated)
                                }
                            }
                        } label: {
                            Label("撤销上次分镜编辑", systemImage: "arrow.uturn.backward")
                        }
                        Button {
                            Task {
                                if let updated = await onEditStoryboardShot(0, .reanalyze) {
                                    apply(updated)
                                }
                            }
                        } label: {
                            Label("局部重新分析", systemImage: "sparkles")
                        }
                    } label: {
                        Label("分镜工具", systemImage: "timeline.selection")
                    }
                }
            }
        }
        .sheet(isPresented: $isEditing) { editSheet }
        .sheet(isPresented: $isEditingContext) {
            UserContextEditSheet(text: contextDraft) { newText in
                Task {
                    let trimmed = newText.trimmingCharacters(in: .whitespacesAndNewlines)
                    if let updated = await onUpdateScript({ $0.withUserContext(trimmed.isEmpty ? nil : trimmed) }) {
                        revisedScript = updated
                    }
                }
            }
        }
        .sheet(isPresented: $isEditingFacts) {
            ScriptFactsEditSheet(draft: factsDraft) { draft in
                Task {
                    if let updated = await onUpdateScript({ draft.applied(to: $0) }) {
                        revisedScript = updated
                    }
                }
            }
        }
        .sheet(item: $editingShot) { shot in
            ShotNarrationEditSheet(shot: shot) { newNarration in
                Task {
                    let index = shot.index
                    if let updated = await onEditStoryboardShot(index, .editDialogue(newNarration)) {
                        apply(updated)
                    }
                }
            }
        }
        .sheet(item: $editingBoundary) { context in
            BoundaryEditSheet(context: context) { seconds in
                Task {
                    if let updated = await onEditStoryboardShot(context.shotIndex, .moveEndBoundary(toSeconds: seconds)) {
                        apply(updated)
                    }
                }
            }
        }
        .sheet(item: $editingPlan) { context in
            PlanEditSheet(context: context) { values in
                Task {
                    if let updated = await onEditStoryboardShot(context.shotIndex, .editPlan(values)) {
                        apply(updated)
                    }
                }
            }
        }
        #if os(iOS)
        .sheet(item: $shareParcel) { parcel in
            ShareSheet(items: parcel.items)
        }
        #endif
    }

    /// Text/URL clips carry their content as editable body text; video breakdowns are structured
    /// scripts (their 台词 is auto-corrected during analysis), so they aren't free-text editable here.
    private var canEditContent: Bool {
        item.breakdown == nil && !(item.bodyText ?? "").isEmpty
    }

    private func apply(_ presentation: StoryboardEditPresentation) {
        revisedScript = presentation.script
        revisedStoryboard = presentation.document
        var parts = ["影响镜头：\(presentation.changedShotIDs.joined(separator: ", "))"]
        if !presentation.changedFields.isEmpty {
            parts.append("字段：\(presentation.changedFields.joined(separator: ", "))")
        }
        if let remap = presentation.remapSummary {
            parts.append("映射：\(remap)")
        }
        if !presentation.invalidatedStages.isEmpty {
            parts.append("待重算：\(presentation.invalidatedStages.joined(separator: " → "))")
        }
        editFeedback = parts.joined(separator: "；")
    }

    /// Only indexed clips have retrievable content, so only they can be asked about.
    private var canAsk: Bool {
        item.state == .indexed
    }

    private nonisolated static func replacingNarration(_ script: Script, shotIndex: Int, narration: String) -> Script {
        let trimmed = narration.trimmingCharacters(in: .whitespacesAndNewlines)
        let shots = script.shots.map { shot -> StoryboardShot in
            guard shot.index == shotIndex else { return shot }
            return StoryboardShot(
                index: shot.index,
                startSeconds: shot.startSeconds,
                endSeconds: shot.endSeconds,
                narration: trimmed.isEmpty ? nil : trimmed,
                visualDescription: shot.visualDescription,
                pacingNote: shot.pacingNote,
                onScreenText: shot.onScreenText
            )
        }
        return Script(
            id: script.id,
            videoSourceID: script.videoSourceID,
            title: script.title,
            summary: script.summary,
            shots: shots,
            createdAt: script.createdAt,
            hookStructure: script.hookStructure,
            visualElements: script.visualElements,
            characters: script.characters,
            degradationNote: script.degradationNote,
            userContext: script.userContext
        )
    }

    /// The local video file backing this breakdown, used to render per-shot frame thumbnails. Video
    /// clips store their imported copy as the source URL; nil for web/text clips (no thumbnails).
    private var breakdownVideoURL: URL? {
        guard let url = item.sourceURL, url.isFileURL else { return nil }
        return url
    }

    #if os(iOS)
    /// Bundles the handoff script text with one frame per shot so 投喂 can carry reference stills
    /// (for 豆包/即梦) alongside the text. Frames are decoded on demand from the local video.
    private func prepareShareWithFrames(_ shots: [StoryboardShot]) async {
        var items: [Any] = [item.handoffText]
        if let url = breakdownVideoURL {
            for shot in shots.sorted(by: { $0.index < $1.index }) {
                if let image = await ShotThumbnailCache.shared.load(url: url, seconds: shot.startSeconds, maxSize: 1080) {
                    items.append(image)
                }
            }
        }
        shareParcel = ShareParcel(items: items)
    }
    #endif

    private var editSheet: some View {
        NavigationStack {
            Form {
                Section("内容") {
                    TextEditor(text: $editDraft)
                        .frame(minHeight: 220)
                }
                Text("订正后会重新索引，问答会基于修正后的内容。")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            .navigationTitle("编辑内容")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("取消") { isEditing = false }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("保存") {
                        onSaveEdit(editDraft)
                        isEditing = false
                    }
                    .disabled(editDraft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                }
            }
        }
    }
}

private struct StoryboardSourceShotRow: View {
    let segment: ShotSegment
    let shot: StoryboardShotV2?

    init(document: StoryboardDocumentV2, index: Int) {
        let selected = document.shotGraph.shots[index]
        segment = selected
        shot = document.shots.first { $0.id == selected.id }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 5) {
            Text("\(segment.id.rawValue)  \(segment.timeRange.startSeconds.formatted(.number.precision(.fractionLength(2))))–\(segment.timeRange.endSeconds.formatted(.number.precision(.fractionLength(2))))s")
                .font(.subheadline.weight(.semibold))
            if let shot, !shot.observedFacts.facts.isEmpty {
                ForEach(shot.observedFacts.facts) { fact in
                    Text("\(fact.field.rawValue)：\(fact.value)")
                        .font(.footnote)
                    Text("证据：\(fact.evidenceIDs.map(\.rawValue).joined(separator: ", "))")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                }
            } else {
                Text("暂无可证实事实")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            if let flags = shot?.observedFacts.reviewFlags, !flags.isEmpty {
                Text("需复核：\(flags.joined(separator: ", "))")
                    .font(.caption)
                    .foregroundStyle(.orange)
            }
        }
    }
}

private struct BoundaryEditContext: Identifiable, Hashable {
    var id: Int { shotIndex }
    let shotIndex: Int
    let lower: Double
    let upper: Double
    let value: Double
}

private struct BoundaryEditSheet: View {
    let context: BoundaryEditContext
    let save: (Double) -> Void
    @Environment(\.dismiss) private var dismiss
    @State private var value: Double

    init(context: BoundaryEditContext, save: @escaping (Double) -> Void) {
        self.context = context
        self.save = save
        _value = State(initialValue: min(context.upper, max(context.lower, context.value)))
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("镜头结束边界") {
                    Slider(value: $value, in: context.lower...context.upper)
                    LabeledContent("时间", value: "\(value.formatted(.number.precision(.fractionLength(2)))) 秒")
                }
                Text("本地 ShotGraph 仍是事实时间轴；移动边界会保持相邻镜头连续，并只使受影响镜头的关键帧、证据、理解和索引失效。")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            .navigationTitle("调整边界")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) { Button("取消") { dismiss() } }
                ToolbarItem(placement: .confirmationAction) {
                    Button("保存") { save(value); dismiss() }
                }
            }
        }
    }
}

private struct PlanEditContext: Identifiable, Hashable {
    var id: Int { shotIndex }
    let shotIndex: Int
    let plan: ShotProductionPlan?
}

private struct PlanEditSheet: View {
    let context: PlanEditContext
    let save: (StoryboardPlanEditValues) -> Void
    @Environment(\.dismiss) private var dismiss
    @State private var purpose: String
    @State private var subjectAction: String
    @State private var dialogue: String
    @State private var copy: String
    @State private var notes: String

    init(context: PlanEditContext, save: @escaping (StoryboardPlanEditValues) -> Void) {
        self.context = context
        self.save = save
        _purpose = State(initialValue: context.plan?.purpose ?? "")
        _subjectAction = State(initialValue: context.plan?.subjectAction ?? "")
        _dialogue = State(initialValue: context.plan?.dialogueOrVO ?? "")
        _copy = State(initialValue: context.plan?.onScreenCopy ?? "")
        _notes = State(initialValue: context.plan?.productionNotes ?? "")
    }

    var body: some View {
        NavigationStack {
            Form {
                TextField("镜头目的", text: $purpose, axis: .vertical)
                TextField("主体动作", text: $subjectAction, axis: .vertical)
                TextField("台词 / 旁白", text: $dialogue, axis: .vertical)
                TextField("屏幕文字", text: $copy, axis: .vertical)
                TextField("制作备注", text: $notes, axis: .vertical)
                Text("保存后的字段会标为人工来源并锁定；后续局部重分析不得覆盖。")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            .navigationTitle("编辑专业字段")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) { Button("取消") { dismiss() } }
                ToolbarItem(placement: .confirmationAction) {
                    Button("保存") {
                        save(StoryboardPlanEditValues(
                            purpose: purpose.trimmedNil,
                            subjectAction: subjectAction.trimmedNil,
                            dialogueOrVO: dialogue.trimmedNil,
                            onScreenCopy: copy.trimmedNil,
                            productionNotes: notes.trimmedNil
                        ))
                        dismiss()
                    }
                }
            }
        }
    }
}

private extension String {
    var trimmedNil: String? {
        let value = trimmingCharacters(in: .whitespacesAndNewlines)
        return value.isEmpty ? nil : value
    }
}

/// Editable understanding-facts of a breakdown (title/summary/爆点结构 fields).
private struct ScriptFactsDraft {
    var title = ""
    var summary = ""
    var openingHook = ""
    var retentionDevices = ""
    var payoff = ""
    var callToAction = ""
    var whyItWorks = ""

    init() {}

    init(script: Script) {
        title = script.title
        summary = script.summary
        openingHook = script.hookStructure?.openingHook ?? ""
        retentionDevices = script.hookStructure?.retentionDevices.joined(separator: "、") ?? ""
        payoff = script.hookStructure?.payoff ?? ""
        callToAction = script.hookStructure?.callToAction ?? ""
        whyItWorks = script.hookStructure?.whyItWorks ?? ""
    }

    func applied(to script: Script) -> Script {
        let devices = retentionDevices
            .split(whereSeparator: { $0 == "、" || $0 == "," || $0 == "，" || $0 == "\n" })
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        let hookFieldsEmpty = openingHook.trimmingCharacters(in: .whitespaces).isEmpty
            && devices.isEmpty
            && payoff.trimmingCharacters(in: .whitespaces).isEmpty
            && callToAction.trimmingCharacters(in: .whitespaces).isEmpty
            && whyItWorks.trimmingCharacters(in: .whitespaces).isEmpty
        let hook: HookAnalysis? = hookFieldsEmpty ? script.hookStructure : HookAnalysis(
            openingHook: openingHook.trimmingCharacters(in: .whitespacesAndNewlines),
            retentionDevices: devices,
            payoff: payoff.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? nil : payoff.trimmingCharacters(in: .whitespacesAndNewlines),
            callToAction: callToAction.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? nil : callToAction.trimmingCharacters(in: .whitespacesAndNewlines),
            whyItWorks: whyItWorks.trimmingCharacters(in: .whitespacesAndNewlines),
            hookType: script.hookStructure?.hookType ?? .other
        )
        return Script(
            id: script.id,
            videoSourceID: script.videoSourceID,
            title: title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? script.title : title.trimmingCharacters(in: .whitespacesAndNewlines),
            summary: summary.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? script.summary : summary.trimmingCharacters(in: .whitespacesAndNewlines),
            shots: script.shots,
            createdAt: script.createdAt,
            hookStructure: hook,
            visualElements: script.visualElements,
            characters: script.characters,
            degradationNote: script.degradationNote,
            userContext: script.userContext
        )
    }
}

private struct UserContextEditSheet: View {
    @State var text: String
    let onSave: (String) -> Void
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    TextEditor(text: $text)
                        .frame(minHeight: 140)
                } footer: {
                    Text("写下这条视频的梗、题材、真实人物/战队等背景。「AI 重新分析」会基于它重新理解爆点，重拆也会带上它。")
                }
            }
            .navigationTitle("视频背景")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("取消") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("保存") {
                        onSave(text)
                        dismiss()
                    }
                }
            }
        }
        .presentationDetents([.medium, .large])
    }
}

private struct ScriptFactsEditSheet: View {
    @State var draft: ScriptFactsDraft
    let onSave: (ScriptFactsDraft) -> Void
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            Form {
                Section("标题与摘要") {
                    TextField("标题", text: $draft.title)
                    TextField("摘要", text: $draft.summary, axis: .vertical)
                        .lineLimit(2...4)
                }
                Section {
                    TextField("钩子（前 3 秒）", text: $draft.openingHook, axis: .vertical)
                        .lineLimit(1...3)
                    TextField("留人手法（、分隔）", text: $draft.retentionDevices, axis: .vertical)
                        .lineLimit(1...3)
                    TextField("爆点/反转", text: $draft.payoff, axis: .vertical)
                        .lineLimit(1...3)
                    TextField("CTA（可空）", text: $draft.callToAction, axis: .vertical)
                        .lineLimit(1...2)
                    TextField("为什么成立", text: $draft.whyItWorks, axis: .vertical)
                        .lineLimit(2...5)
                } header: {
                    Text("剧情点（爆点结构）")
                } footer: {
                    Text("改完会重建检索索引，问答与洞察范式都会基于修正后的内容。")
                }
            }
            .navigationTitle("编辑剧本信息")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("取消") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("保存") {
                        onSave(draft)
                        dismiss()
                    }
                }
            }
        }
    }
}

private struct ShotNarrationEditSheet: View {
    let shot: StoryboardShot
    let onSave: (String) -> Void
    @State private var text: String
    @Environment(\.dismiss) private var dismiss

    init(shot: StoryboardShot, onSave: @escaping (String) -> Void) {
        self.shot = shot
        self.onSave = onSave
        _text = State(initialValue: shot.narration ?? "")
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("台词") {
                    TextEditor(text: $text)
                        .frame(minHeight: 100)
                }
                if !shot.onScreenText.isEmpty {
                    Section {
                        Text(shot.onScreenText.joined(separator: " / "))
                            .font(.footnote)
                            .foregroundStyle(.secondary)
                            .textSelection(.enabled)
                        Button {
                            text = shot.onScreenText.joined(separator: "，")
                        } label: {
                            Label("用字幕填入", systemImage: "text.insert")
                        }
                    } header: {
                        Text("字幕参考")
                    } footer: {
                        Text("字幕是作者自己压的，通常比语音识别准。")
                    }
                }
            }
            .navigationTitle("订正分镜 \(shot.index + 1) 台词")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("取消") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("保存") {
                        onSave(text)
                        dismiss()
                    }
                }
            }
        }
        .presentationDetents([.medium, .large])
    }
}

private struct HookStructureView: View {
    let hook: HookAnalysis

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            labeledLine("钩子", hook.openingHook)
            if !hook.retentionDevices.isEmpty {
                labeledLine("留人", hook.retentionDevices.joined(separator: "、"))
            }
            if let payoff = hook.payoff, !payoff.isEmpty {
                labeledLine("爆点", payoff)
            }
            if let cta = hook.callToAction, !cta.isEmpty {
                labeledLine("CTA", cta)
            }
            if !hook.whyItWorks.isEmpty {
                labeledLine("为什么成立", hook.whyItWorks)
            }
        }
        .textSelection(.enabled)
    }

    @ViewBuilder
    private func labeledLine(_ label: String, _ value: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label)
                .font(.caption.weight(.semibold))
                .foregroundStyle(.secondary)
            Text(value)
                .font(.subheadline)
        }
    }
}

private struct ShotRowView: View {
    let shot: StoryboardShot
    var videoURL: URL? = nil

    var body: some View {
        HStack(alignment: .top, spacing: 10) {
            #if os(iOS)
            if let videoURL {
                // Midpoint, not startSeconds: a shot's first frame often catches the cut/transition
                // (mouth closed, motion blur) — the middle is the representative moment.
                ShotThumbnail(
                    videoURL: videoURL,
                    seconds: (shot.startSeconds + max(shot.startSeconds, shot.endSeconds)) / 2,
                    startSeconds: shot.startSeconds,
                    endSeconds: shot.endSeconds,
                    shotIndex: shot.index
                )
            }
            #endif

            VStack(alignment: .leading, spacing: 4) {
                Text("分镜 \(shot.index + 1)  \(timeRange)")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.secondary)
                if let narration = shot.narration, !narration.isEmpty {
                    Text("台词: \(narration)").font(.subheadline)
                }
                if !shot.onScreenText.isEmpty {
                    Text("字幕: \(shot.onScreenText.joined(separator: " / "))")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                if !shot.visualDescription.isEmpty {
                    Text("画面: \(shot.visualDescription)").font(.subheadline)
                }
                if let pacing = shot.pacingNote, !pacing.isEmpty {
                    Text("节奏: \(pacing)").font(.caption).foregroundStyle(.secondary)
                }
            }
            .textSelection(.enabled)
        }
        .padding(.vertical, 2)
    }

    private var timeRange: String {
        "\(format(shot.startSeconds))–\(format(shot.endSeconds))"
    }

    private func format(_ seconds: Double) -> String {
        let safe = seconds.isFinite ? seconds : 0
        return String(format: "%.1fs", safe)
    }
}

#if os(iOS)
/// A per-shot frame thumbnail, decoded on demand from the local video at the shot's start time and
/// cached so re-scrolling the storyboard doesn't re-decode. Tap to view the frame full-screen.
private struct ShotThumbnail: View {
    let videoURL: URL
    let seconds: Double
    let startSeconds: Double
    let endSeconds: Double
    let shotIndex: Int
    @State private var image: UIImage?
    @State private var isEnlarged = false

    var body: some View {
        Group {
            if let image {
                Image(uiImage: image)
                    .resizable()
                    .aspectRatio(contentMode: .fill)
            } else {
                RoundedRectangle(cornerRadius: 8)
                    .fill(Color.secondary.opacity(0.15))
                    .overlay(Image(systemName: "photo").foregroundStyle(.secondary))
            }
        }
        .frame(width: 60, height: 84)
        .clipShape(RoundedRectangle(cornerRadius: 8))
        .contentShape(RoundedRectangle(cornerRadius: 8))
        .onTapGesture { if image != nil { isEnlarged = true } }
        .task(id: seconds) {
            image = await ShotThumbnailCache.shared.load(url: videoURL, seconds: seconds)
        }
        .fullScreenCover(isPresented: $isEnlarged) {
            ShotRangePlaybackPreview(
                videoURL: videoURL,
                startSeconds: startSeconds,
                endSeconds: endSeconds,
                shotIndex: shotIndex
            )
        }
        .accessibilityLabel("分镜 \(shotIndex + 1) 画面")
    }
}

/// Full-screen player constrained to the selected authoritative shot boundary.
private struct ShotRangePlaybackPreview: View {
    let videoURL: URL
    let startSeconds: Double
    let endSeconds: Double
    let shotIndex: Int
    @Environment(\.dismiss) private var dismiss
    @State private var player: AVPlayer?

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            if let player {
                VideoPlayer(player: player)
            } else {
                ProgressView().tint(.white)
            }
            VStack {
                HStack {
                    Spacer()
                    Button {
                        player?.pause()
                        dismiss()
                    } label: {
                        Image(systemName: "xmark.circle.fill")
                            .font(.largeTitle)
                            .foregroundStyle(.white.opacity(0.85))
                            .padding()
                    }
                    .accessibilityLabel("关闭")
                }
                Spacer()
            }
        }
        .task {
            let playback = AVPlayer(url: videoURL)
            player = playback
            await playback.seek(to: CMTime(seconds: max(0, startSeconds), preferredTimescale: 600))
            playback.play()
            while !Task.isCancelled {
                let current = playback.currentTime().seconds
                if current.isFinite, current >= endSeconds {
                    await playback.seek(to: CMTime(seconds: max(0, startSeconds), preferredTimescale: 600))
                    playback.play()
                }
                try? await Task.sleep(for: .milliseconds(100))
            }
            playback.pause()
        }
    }
}

/// Small in-memory cache + decoder for video frame thumbnails. Keyed by (url, ~0.1s, size) so a
/// row thumbnail and its full-screen preview are cached independently.
@MainActor
private final class ShotThumbnailCache {
    static let shared = ShotThumbnailCache()
    private var cache: [String: UIImage] = [:]

    func load(url: URL, seconds: Double, maxSize: CGFloat = 320) async -> UIImage? {
        let key = "\(url.absoluteString)#\(Int(seconds * 10))@\(Int(maxSize))"
        if let cached = cache[key] { return cached }
        let image = await Self.decode(url: url, seconds: seconds, maxSize: maxSize)
        if let image { cache[key] = image }
        return image
    }

    private static func decode(url: URL, seconds: Double, maxSize: CGFloat) async -> UIImage? {
        let generator = AVAssetImageGenerator(asset: AVURLAsset(url: url))
        generator.appliesPreferredTrackTransform = true
        generator.requestedTimeToleranceBefore = CMTime(seconds: 0.3, preferredTimescale: 600)
        generator.requestedTimeToleranceAfter = CMTime(seconds: 0.3, preferredTimescale: 600)
        generator.maximumSize = CGSize(width: maxSize, height: maxSize)
        let time = CMTime(seconds: max(0, seconds), preferredTimescale: 600)
        guard let cgImage = try? await generator.image(at: time).image else {
            return nil
        }
        return UIImage(cgImage: cgImage)
    }
}
#endif

private struct StateBadge: View {
    let state: ClipState

    var body: some View {
        Text(state.rawValue.capitalized)
            .font(.caption.weight(.semibold))
            .foregroundStyle(foreground)
            .padding(.horizontal, 8)
            .padding(.vertical, 4)
            .background(background, in: Capsule())
    }

    private var foreground: Color {
        switch state {
        case .indexed:
            .green
        case .failed:
            .red
        case .fetching, .indexing, .transcribing, .analyzing, .scripting:
            .blue
        case .queued:
            .secondary
        }
    }

    private var background: Color {
        foreground.opacity(0.14)
    }
}

/// A prepared share payload (script text + shot stills) identified for `.sheet(item:)`.
private struct ShareParcel: Identifiable {
    let id = UUID()
    let items: [Any]
}

#if os(iOS)
/// Bridges UIActivityViewController so 投喂 can share mixed content (text + reference stills).
private struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ controller: UIActivityViewController, context: Context) {}
}
#endif
